#!/bin/bash

###
### Main Executor
###
### Script that validates software dependencies and call VRE_RUNNER.py
###


DEPENDENCIES=("python3")  # TODO add your software dependencies (e.g. DEPENDENCIES=("Rscript","docker")
PROGNAME="VRE_RUNNER.py"

# Validate dependencies

REALPATH="$(realpath "$0")"
BASEDIR="$(dirname "$REALPATH")"

case "$BASEDIR" in
/*)
  true
  ;;
*)
  BASEDIR="${PWD}/$BASEDIR"
  ;;
esac

for prog in $(echo $DEPENDENCIES | sed "s/,/ /g"); do
  type -a "$prog" >/dev/null
  if [ $? -ne 0 ]; then
    echo "UNCONFIGURED: No $prog executable found" 1>&2
    exit 1
  fi
done

# Run VRE_RUNNER

#source "$BASEDIR"/venv/bin/activate

#source /opt/conda/etc/profile.d/conda.sh

source /home/bscuser/anaconda3/etc/profile.d/conda.sh
echo "${BASEDIR}"

#conda env create -f  "${BASEDIR}"/environment.yml
conda activate 3dshaper



#exec python "${BASEDIR}"/setup.py build; pip install "${BASEDIR}"/requirments.txt; python "${BASEDIR}"/setup.py install && python3 -u "${BASEDIR}"/"${PROGNAME}" "$@"

exec python3 -u "${BASEDIR}"/"${PROGNAME}" "$@"

exit 1
